extends:
  - recommended

apis:
  main:
    root: ./src/openapi.yaml
    rules:
      tag-description: off
      operation-operationId: off
      no-unresolved-refs: error
      operation-2xx-response: error
      operation-singular-tag: error
      no-unused-components: error
      no-ambiguous-paths: error
theme:
  openapi:
    requiredPropsFirst: true
    generateCodeSamples:
      languages:
        - lang: curl
        - lang: Go
        - lang: Java
        - lang: JavaScript
        - lang: PHP
    theme:
      logo:
        gutter: 2em
      colors:
        primary:
          main: '#0D9488'
      fab:
        color: '#0D9488'
      overrides:
        DownloadButton:
          custom: 'border-radius: 0.25em'
      sidebar:
        backgroundColor: '#f3f4f6'
      rightPanel:
        backgroundColor: '#111827'